# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees: [ "marko-bekhta" ]
    # We don't trigger Jenkins or GitHub Actions builds on pull requests from dependabot,
    # so we can safely use a high limit here.
    open-pull-requests-limit: 20
    labels:
      - build-dependencies
      # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      build-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "org.apache.commons:commons-lang3" # A single dependency name
        #          - ""  # A wildcard string that matches multiple dependency names
        #          - "*"       # A wildcard that matches all dependencies in the package
        # ecosystem. Note: using "*" may open a large pull request
        # Define patterns to exclude dependencies from the group (based on
        # dependency name)
      #        exclude-patterns:
      #          - "gc_ruboconfig"
      #          - "gocardless-*"
      maven-plugins:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*plugin*" # A single dependency name
          - "*maven*" # A single dependency name
        #          - ""  # A wildcard string that matches multiple dependency names
        #          - "*"       # A wildcard that matches all dependencies in the package
        # ecosystem. Note: using "*" may open a large pull request
        # Define patterns to exclude dependencies from the group (based on
        # dependency name)
      #        exclude-patterns:
      #          - "gc_ruboconfig"
      #          - "gocardless-*"
      drivers:
        patterns:
          - "com.h2database:h2"
    allow:
      - dependency-name: "*"